// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: pbf/transfers/api.proto

package transfers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pbf_transfers_api_proto protoreflect.FileDescriptor

const file_pbf_transfers_api_proto_rawDesc = "" +
	"\n" +
	"\x17pbf/transfers/api.proto\x12\ttransfers\x1a\x1apbf/transfers/search.proto29\n" +
	"\x03API\x122\n" +
	"\x06Search\x12\x12.transfers.SearchI\x1a\x12.transfers.SearchO\"\x00B\x0eZ\f./;transfersb\x06proto3"

var file_pbf_transfers_api_proto_goTypes = []any{
	(*SearchI)(nil), // 0: transfers.SearchI
	(*SearchO)(nil), // 1: transfers.SearchO
}
var file_pbf_transfers_api_proto_depIdxs = []int32{
	0, // 0: transfers.API.Search:input_type -> transfers.SearchI
	1, // 1: transfers.API.Search:output_type -> transfers.SearchO
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbf_transfers_api_proto_init() }
func file_pbf_transfers_api_proto_init() {
	if File_pbf_transfers_api_proto != nil {
		return
	}
	file_pbf_transfers_search_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbf_transfers_api_proto_rawDesc), len(file_pbf_transfers_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pbf_transfers_api_proto_goTypes,
		DependencyIndexes: file_pbf_transfers_api_proto_depIdxs,
	}.Build()
	File_pbf_transfers_api_proto = out.File
	file_pbf_transfers_api_proto_goTypes = nil
	file_pbf_transfers_api_proto_depIdxs = nil
}
