// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: pbf/transfers/search.proto

package transfers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchI is the input for searching transfers.
//
//	{
//	    "filter": {
//	        "paging": {
//	            "kind": "page",
//	            "start": "0",
//	            "stop": "49"
//	        }
//	    },
//	    "search": [
//	        {
//	            "address": "0x4838...5f97"
//	        }
//	    ]
//	}
type SearchI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *SearchI_Filter        `protobuf:"bytes,100,opt,name=filter,proto3" json:"filter,omitempty"`
	Search        []*SearchI_Object      `protobuf:"bytes,200,rep,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchI) Reset() {
	*x = SearchI{}
	mi := &file_pbf_transfers_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchI) ProtoMessage() {}

func (x *SearchI) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_transfers_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchI.ProtoReflect.Descriptor instead.
func (*SearchI) Descriptor() ([]byte, []int) {
	return file_pbf_transfers_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchI) GetFilter() *SearchI_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SearchI) GetSearch() []*SearchI_Object {
	if x != nil {
		return x.Search
	}
	return nil
}

type SearchI_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *SearchI_Filter_Paging `protobuf:"bytes,100,opt,name=paging,proto3" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchI_Filter) Reset() {
	*x = SearchI_Filter{}
	mi := &file_pbf_transfers_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchI_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchI_Filter) ProtoMessage() {}

func (x *SearchI_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_transfers_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchI_Filter.ProtoReflect.Descriptor instead.
func (*SearchI_Filter) Descriptor() ([]byte, []int) {
	return file_pbf_transfers_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchI_Filter) GetPaging() *SearchI_Filter_Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

type SearchI_Filter_Paging struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,100,opt,name=kind,proto3" json:"kind,omitempty"`
	Start         string                 `protobuf:"bytes,200,opt,name=start,proto3" json:"start,omitempty"`
	Stop          string                 `protobuf:"bytes,300,opt,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchI_Filter_Paging) Reset() {
	*x = SearchI_Filter_Paging{}
	mi := &file_pbf_transfers_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchI_Filter_Paging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchI_Filter_Paging) ProtoMessage() {}

func (x *SearchI_Filter_Paging) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_transfers_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchI_Filter_Paging.ProtoReflect.Descriptor instead.
func (*SearchI_Filter_Paging) Descriptor() ([]byte, []int) {
	return file_pbf_transfers_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchI_Filter_Paging) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SearchI_Filter_Paging) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *SearchI_Filter_Paging) GetStop() string {
	if x != nil {
		return x.Stop
	}
	return ""
}

type SearchI_Object struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// address is the wallet address for which transfers are searched.
	Address       string `protobuf:"bytes,100,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchI_Object) Reset() {
	*x = SearchI_Object{}
	mi := &file_pbf_transfers_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchI_Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchI_Object) ProtoMessage() {}

func (x *SearchI_Object) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_transfers_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchI_Object.ProtoReflect.Descriptor instead.
func (*SearchI_Object) Descriptor() ([]byte, []int) {
	return file_pbf_transfers_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchI_Object) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// SearchO is the output for searching transfers.
//
//	{
//	    "result": [
//	        {
//	            "address": "0x4838...5f97",
//	            "transfers": [
//	                {
//	                    "amount": "420000000000000000000",
//	                    "created_at": "1689001255",
//	                    "id": "a9526eca-953e-49f7-aa4c-12fc06132124",
//	                    "to": "0x4838...5f97"
//	                }
//	            ]
//	        }
//	    ]
//	}
type SearchO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*SearchO_Object      `protobuf:"bytes,100,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchO) Reset() {
	*x = SearchO{}
	mi := &file_pbf_transfers_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchO) ProtoMessage() {}

func (x *SearchO) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_transfers_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchO.ProtoReflect.Descriptor instead.
func (*SearchO) Descriptor() ([]byte, []int) {
	return file_pbf_transfers_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchO) GetResult() []*SearchO_Object {
	if x != nil {
		return x.Result
	}
	return nil
}

type SearchO_Object struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// address is the wallet address for which transfers are searched.
	Address string `protobuf:"bytes,100,opt,name=address,proto3" json:"address,omitempty"`
	// transfers is the list of transfers associated to the given wallet address.
	Transfers     []*SearchO_Object_Transfer `protobuf:"bytes,200,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchO_Object) Reset() {
	*x = SearchO_Object{}
	mi := &file_pbf_transfers_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchO_Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchO_Object) ProtoMessage() {}

func (x *SearchO_Object) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_transfers_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchO_Object.ProtoReflect.Descriptor instead.
func (*SearchO_Object) Descriptor() ([]byte, []int) {
	return file_pbf_transfers_search_proto_rawDescGZIP(), []int{5}
}

func (x *SearchO_Object) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SearchO_Object) GetTransfers() []*SearchO_Object_Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

type SearchO_Object_Transfer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// amount is the bigint value of the onchain transfer. It is the caller's
	// responsibility to know the number of decimals for any given token transfer.
	Amount string `protobuf:"bytes,100,opt,name=amount,proto3" json:"amount,omitempty"`
	// created_at is the unix timestamp in seconds at which this transfer got
	// created.
	CreatedAt string `protobuf:"bytes,200,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// id is the UUID of the given transfer object.
	Id string `protobuf:"bytes,300,opt,name=id,proto3" json:"id,omitempty"`
	// to is the to field of this transfer, the wallet address to which tokens
	// have been sent.
	To            string `protobuf:"bytes,400,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchO_Object_Transfer) Reset() {
	*x = SearchO_Object_Transfer{}
	mi := &file_pbf_transfers_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchO_Object_Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchO_Object_Transfer) ProtoMessage() {}

func (x *SearchO_Object_Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_transfers_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchO_Object_Transfer.ProtoReflect.Descriptor instead.
func (*SearchO_Object_Transfer) Descriptor() ([]byte, []int) {
	return file_pbf_transfers_search_proto_rawDescGZIP(), []int{6}
}

func (x *SearchO_Object_Transfer) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SearchO_Object_Transfer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SearchO_Object_Transfer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchO_Object_Transfer) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

var File_pbf_transfers_search_proto protoreflect.FileDescriptor

const file_pbf_transfers_search_proto_rawDesc = "" +
	"\n" +
	"\x1apbf/transfers/search.proto\x12\ttransfers\"p\n" +
	"\aSearchI\x121\n" +
	"\x06filter\x18d \x01(\v2\x19.transfers.SearchI_FilterR\x06filter\x122\n" +
	"\x06search\x18\xc8\x01 \x03(\v2\x19.transfers.SearchI_ObjectR\x06search\"J\n" +
	"\x0eSearchI_Filter\x128\n" +
	"\x06paging\x18d \x01(\v2 .transfers.SearchI_Filter_PagingR\x06paging\"W\n" +
	"\x15SearchI_Filter_Paging\x12\x12\n" +
	"\x04kind\x18d \x01(\tR\x04kind\x12\x15\n" +
	"\x05start\x18\xc8\x01 \x01(\tR\x05start\x12\x13\n" +
	"\x04stop\x18\xac\x02 \x01(\tR\x04stop\"*\n" +
	"\x0eSearchI_Object\x12\x18\n" +
	"\aaddress\x18d \x01(\tR\aaddress\"<\n" +
	"\aSearchO\x121\n" +
	"\x06result\x18d \x03(\v2\x19.transfers.SearchO_ObjectR\x06result\"m\n" +
	"\x0eSearchO_Object\x12\x18\n" +
	"\aaddress\x18d \x01(\tR\aaddress\x12A\n" +
	"\ttransfers\x18\xc8\x01 \x03(\v2\".transfers.SearchO_Object_TransferR\ttransfers\"s\n" +
	"\x17SearchO_Object_Transfer\x12\x16\n" +
	"\x06amount\x18d \x01(\tR\x06amount\x12\x1e\n" +
	"\n" +
	"created_at\x18\xc8\x01 \x01(\tR\tcreatedAt\x12\x0f\n" +
	"\x02id\x18\xac\x02 \x01(\tR\x02id\x12\x0f\n" +
	"\x02to\x18\x90\x03 \x01(\tR\x02toB\x0eZ\f./;transfersb\x06proto3"

var (
	file_pbf_transfers_search_proto_rawDescOnce sync.Once
	file_pbf_transfers_search_proto_rawDescData []byte
)

func file_pbf_transfers_search_proto_rawDescGZIP() []byte {
	file_pbf_transfers_search_proto_rawDescOnce.Do(func() {
		file_pbf_transfers_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbf_transfers_search_proto_rawDesc), len(file_pbf_transfers_search_proto_rawDesc)))
	})
	return file_pbf_transfers_search_proto_rawDescData
}

var file_pbf_transfers_search_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pbf_transfers_search_proto_goTypes = []any{
	(*SearchI)(nil),                 // 0: transfers.SearchI
	(*SearchI_Filter)(nil),          // 1: transfers.SearchI_Filter
	(*SearchI_Filter_Paging)(nil),   // 2: transfers.SearchI_Filter_Paging
	(*SearchI_Object)(nil),          // 3: transfers.SearchI_Object
	(*SearchO)(nil),                 // 4: transfers.SearchO
	(*SearchO_Object)(nil),          // 5: transfers.SearchO_Object
	(*SearchO_Object_Transfer)(nil), // 6: transfers.SearchO_Object_Transfer
}
var file_pbf_transfers_search_proto_depIdxs = []int32{
	1, // 0: transfers.SearchI.filter:type_name -> transfers.SearchI_Filter
	3, // 1: transfers.SearchI.search:type_name -> transfers.SearchI_Object
	2, // 2: transfers.SearchI_Filter.paging:type_name -> transfers.SearchI_Filter_Paging
	5, // 3: transfers.SearchO.result:type_name -> transfers.SearchO_Object
	6, // 4: transfers.SearchO_Object.transfers:type_name -> transfers.SearchO_Object_Transfer
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pbf_transfers_search_proto_init() }
func file_pbf_transfers_search_proto_init() {
	if File_pbf_transfers_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbf_transfers_search_proto_rawDesc), len(file_pbf_transfers_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbf_transfers_search_proto_goTypes,
		DependencyIndexes: file_pbf_transfers_search_proto_depIdxs,
		MessageInfos:      file_pbf_transfers_search_proto_msgTypes,
	}.Build()
	File_pbf_transfers_search_proto = out.File
	file_pbf_transfers_search_proto_goTypes = nil
	file_pbf_transfers_search_proto_depIdxs = nil
}
